kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fluentbit-volumeclaim
  namespace: efk-fluentbit
spec:
  storageClassName: pv-fluent-bit
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
